base:
  project: heart_disease-project
  random_state: 42
  target_col: target

data_source:
  s3_source: data/heart.csv

load_data:
  raw_dataset: data/raw/heart.csv

split_data:
  train_path: data/processed/train_heart.csv
  test_path: data/processed/test_heart.csv
  test_size: 0.2
