name: Heart Disease Project

on:
  push:
    branches:
    - main
    pull_request:
      branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.7
      with: 
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requeirements.txt ]; then pip install -r requirements.txt; fi