name: DVC Workflow

on:
  push:
    branches:
      - main

jobs:
  run-dvc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install DVC
        run: |
          pip install dvc

      - name: Pull DVC files
        run: |
          dvc pull

      - name: Run DVC commands
        run: |
          dvc repro
